dataset:
  dataset_name: "cc12m"
  dataset_path: "file:F:/datasets/cc12m/{00000..00469}.tar"
  image_size: 256
  shuffle_size: 1500
  num_images: 10554521
  num_workers: 6
  prefetch_factor: 1
  pin_memory: True
  drop_last: True
train:
  epochs: 5
  batch_size: 240
  unet_number: 1
  unet1_max_batch_size: 12
  unet2_max_batch_size: 6
  load_checkpoint: False
  load_checkpoint_path: "./checkpoint/imagen_medium_checkpoint.pt"
  checkpoint_rate: 1000
  checkpoint_path: "./checkpoint/imagen_medium_checkpoint.pt"
  checkpoint_strict: False
  checkpoint_model_only: False
  non_blocking: True
  use_ema: True
  lr: 0.000015
  eps: 0.00000001
  beta1: 0.9
  beta2: 0.99
  max_grad_norm: None
  amp: True
  group_wd_params: True
  warmup_steps: None
  cosine_decay_max_steps: None
  cond_scale: 5
  sample_texts: ['dog', 'cheeseburger', 'blue car', 'red flowers in a white vase', 'a puppy looking anxiously at a giant donut on the table', 'the milky way galaxy in the style of monet']
model:
  text_encoder_name: "google/t5-v1_1-xl"
  image_sizes: [64, 256]
  cond_drop_prob: 0.1
  timesteps: 1000
  unet1:
    dim: 192
    cond_dim: 512
    dim_mults: [1, 2, 3, 4]
    num_resnet_blocks: 3
    layer_attns: [False, True, True, True]
    layer_cross_attns: [False, True, True, True]
    attn_heads: 8
    ff_mult: 2
    memory_efficient: False
    dropout: 0.1
  unet2:
    dim: 96
    cond_dim: 512
    dim_mults: [1, 2, 4, 8]
    num_resnet_blocks: [2, 4, 8, 8]
    layer_attns: [False, False, False, True]
    layer_cross_attns: [False, False, False, True]
    attn_heads: 8
    ff_mult: 2
    memory_efficient: True
    dropout: 0.1