dataset:
  image_size: 256
  info_file: "coco/dataset_info.pkl"
  captions_per_image: 5
train:
  epochs: 50
  batch_size: 96
  base_unet_max_batch_size: 24
  sr_unet1_max_batch_size: 8
  load_checkpoint: False
  load_checkpoint_path: "./checkpoint/imagen_xl_checkpoint.pt"
  checkpoint_rate: 500
  checkpoint_path: "./checkpoint/imagen_xl_checkpoint.pt"
  use_ema: True
  lr: 0.000001
  eps: 0.00000001
  beta1: 0.9
  beta2: 0.99
  max_grad_norm: None
  amp: True
  group_wd_params: True
  warmup_steps: None
  cosine_decay_max_steps: None
  cond_scale: 5
model:
  text_encoder_name: "google/t5-v1_1-large"
  image_sizes: [64, 256]
  cond_drop_prob: 0.1
  timesteps: 1000
  base_unet:
    dim: 192
    cond_dim: 512
    dim_mults: [1, 2, 3, 4]
    num_resnet_blocks: 3
    layer_attns: [False, True, True, True]
    layer_cross_attns: [False, True, True, True]
    attn_heads: 8
    ff_mult: 2
    memory_efficient: False
    dropout: 0.15
  sr_unet1:
    dim: 96
    cond_dim: 512
    dim_mults: [1, 2, 4, 8]
    num_resnet_blocks: [2, 4, 8, 8]
    layer_attns: [False, False, False, True]
    layer_cross_attns: [False, False, False, True]
    attn_heads: 8
    ff_mult: 2
    memory_efficient: True
    dropout: 0.1